# Generated by Django 3.0.3 on 2020-07-17 21:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chores', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChoreInstance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField()),
                ('done', models.BooleanField(default=False)),
                ('chore', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='instances', to='chores.Chore')),
                ('interval', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='instances', to='chores.ChoreInterval')),
            ],
        ),
    ]
