# Generated by Django 3.0.3 on 2020-07-17 21:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chores', '0002_choreinstance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='choreinstance',
            name='interval',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='instances', to='chores.ChoreInterval'),
        ),
    ]
