# Generated by Django 3.0.3 on 2020-07-17 23:39

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('chores', '0003_auto_20200717_2136'),
    ]

    operations = [
        migrations.AddField(
            model_name='chore',
            name='datetime',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='choreinstance',
            name='interval',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='instances', to='chores.ChoreInterval'),
        ),
    ]
