# Generated by Django 3.0.3 on 2020-07-15 18:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Chore',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('description', models.TextField()),
                ('repeats', models.BooleanField(default=True)),
                ('count_repetitions', models.PositiveIntegerField(default=0)),
                ('completed', models.BooleanField(default=False)),
                ('last_completed_on', models.DateTimeField()),
                ('last_completed_by', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ChoreInterval',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('repeat_start', models.DateTimeField(auto_now_add=True)),
                ('repeat_interval', models.IntegerField(blank=True, null=True)),
                ('repeat_day_of_year', models.IntegerField(blank=True, null=True)),
                ('repeat_day_of_month', models.IntegerField(blank=True, null=True)),
                ('repeat_day_of_week', models.IntegerField(blank=True, null=True)),
                ('repeat_hour_of_day', models.IntegerField(blank=True, null=True)),
                ('repeat_minute_of_hour', models.IntegerField(blank=True, null=True)),
                ('chore', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chore_intervals', to='chores_list.Chore')),
            ],
        ),
    ]
