# Generated by Django 3.0.3 on 2020-07-15 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chores_list', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chore',
            name='last_completed_on',
            field=models.DateTimeField(blank=True),
        ),
    ]
