# Generated by Django 3.0.3 on 2020-07-15 20:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chores_list', '0002_auto_20200715_2000'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chore',
            name='last_completed_by',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
    ]
